### ISSUE TITLE
Add timsTOF Bruker support

### ISSUE THREAD

**Issue by adamscharlotte** [wilhelm-lab/oktoberfest#115]
It would be great if Oktoberfest would also work for the timsTOF Bruker .d as input.

### Minimal requirements

- [x] Allow a new input type: ~"timsTOF"~ "pkl"
- [x] refactor, the mzML output folder to "spectra", because it now can contain either mzML or .pkl
- [x] Adjust CE calibration -> use ransac model
- [x] Add CE calibration plot -> check ransac model plot
- [x] update documentation:
  - [x] document usage of pkl in addition to mzml / raw
  - [x] document added option for ce range in config
  - [x] document added option for ransac ce calib in config
  - [x] combine options into ce_calibration section in config
  - [x] document change from mzML to spectra folder in output
  - [x] refactor raw file -> spectra file and add .d where needed in config

### Optional CCS support:

- [ ] add new config section in models for CCS (ion-mobility) + document
- [x] separate grpc_predict for individual things to predict in the API

## Todos in spectrum-io (@adamscharlotte)

- [x] add the r script to convert .d, sum precursors and store as .pkl
- [x] add the conversion scripts to a new submodule bruker/timsTOF
- [ ] add optional dependencies, i.e. R, and timsR
- [x] check if this is a breaking change and update minor or hotfix version @picciama

## Optional todos in spectrum-fundamentals @adamscharlotte 

- [ ] check conversion from ion_mobility value to observed CCS @adamscharlotte 
- [ ] alignment of predictedCCS and observedCCS, check if we can reuse the irt alignment procedure
- [ ] add deltaCCS = predictedCCS - observedCCS

**Comment by picciama** [comment]
The oktoberfest package now supports the logic for data that come in pkl format. For spectrum-io, I am waiting for what the discussion in #136 results in.
